spring:
  application:
    name: userInfo
  datasource:
    url: jdbc:mysql://localhost:3306/TESTDB?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect


logging:
  file:
    name: C:\Users\vibhuti.a.jain\Documents\code\spring.log #log file path
    max-size: 10MB #log file size
    max-history: 10 #latest number of log files